---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc001-nfs
  namespace: homework
spec:
  storageClassName: "nfs-csi"
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 300Mi
