---
apiVersion: v1
kind: Service
metadata:
  name: staticweb
  namespace: homework
  labels:
    app.kubernetes.io/name: roflmaoinmysoul
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: roflmaoinmysoul
  ports:
  - name: mysql-svc-port
    protocol: TCP
    port: 3306
    targetPort: mysql-port
