---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc001
  namespace: homework
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
