---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "local-storage"
  claimRef:
    name: pvc001
    namespace: homework
  local:
    path: /srv/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: homework
          operator: In
          values:
          - 'true'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc001
  namespace: homework
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
