---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: RoleBinding
#metadata:
#  name: monitoring
#  namespace: homework
#subjects:
## You can specify more than one "subject"
#- kind: ServiceAccount
#  name: monitoring # "name" is case sensitive # should match monitoring
#  apiGroup: ""
#roleRef:
#  # "roleRef" specifies the binding to a Role / ClusterRole
#  kind: Role #this must be Role or ClusterRole
#  name: monitoring # this must match the name of the Role or ClusterRole you wish to bind to
#  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: homework
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: cd # "name" is case sensitive # should match monitoring
  apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: admin # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: ""

