---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/no-provisioner
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  claimRef:
    name: pvc001
    namespace: homework
  local:
    path: /srv/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: homework
          operator: In
          values:
          - 'true'
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "local-storage"
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc001
  namespace: homework
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
